devices([
  "iPhone 8 Plus",
  "iPhone 14 Plus",
])

languages([
  "en-US",
])

scheme("DeepDishLie")
output_directory("./screenshots")
clear_previous_screenshots(true)
#override_status_bar(true)
concurrent_simulators(true)
