devices([
  "iPhone 15 Pro Max",
  "iPhone 14 Plus",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (11-inch) (4th generation)"
])

languages([
  "en-US",
])

scheme("DeepDishLie")
output_directory("./screenshots")
clear_previous_screenshots(true)
#override_status_bar(true)
concurrent_simulators(true)
