devices([
  "iPhone 16 Pro Max",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US",
])

scheme("DeepDishApp")
output_directory("./screenshots")
clear_previous_screenshots(true)
#override_status_bar(true)
concurrent_simulators(true)
